# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: base-auth-sdk-staging
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      name: base-auth-sdk-service
      labels:
        app: base-auth-sdk
        role: backend
        env: staging
    spec:
      containers:
        - name: service
          image: gcr.io/bitclave-jenkins-ci/base-auth-sdk:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          env:
            - name: WIDGET_LOCATION
              value: "auth/widget"

          envFrom:
            - secretRef:
                name: secret-staging-base-auth-sdk

          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 5003

          readinessProbe:
            httpGet:
              path: /
              port: 5003
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 3
